#!/bin/bash

#mpiexec -n 1 ./mmc -options_left -ksp_view

#mpiexec -n 3 ./mmc -options_left -ksp_view -pc_factor_mat_solver_package mumps

#mpiexec -n 4 ./mmc -options_left -ksp_view -pc_factor_mat_solver_package mumps -mat_mumps_icntl_4 2

#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -pc_factor_mat_solver_package mumps -L_scaling_option 1

#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 \
#  -pc_type fieldsplit -pc_fieldsplit_detect_saddle_point -ksp_max_it 3 -pc_fieldsplit_schur_precondition selfp \
#    -fieldsplit_0_pc_type lu -fieldsplit_0_pc_factor_mat_solver_package mumps -fieldsplit_1_pc_type lu -fieldsplit_1_pc_factor_mat_solver_package mumps \
#    -pc_fieldsplit_schur_fact_type diag

#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 \
#  -pc_type fieldsplit -pc_fieldsplit_detect_saddle_point -ksp_max_it 3 -pc_fieldsplit_type schur -fieldsplit_1_pc_type lsc \
#    -fieldsplit_0_pc_type lu -fieldsplit_0_pc_factor_mat_solver_package mumps -pc_fieldsplit_schur_precondition self

#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 \
#  -fieldsplit_option 2 -ksp_max_it 3 -pc_fieldsplit_schur_precondition full -pc_fieldsplit_type schur\
#    -fieldsplit_0_pc_type lu -fieldsplit_0_pc_factor_mat_solver_package mumps -fieldsplit_1_pc_type lu -fieldsplit_1_pc_factor_mat_solver_package mumps

# Direct solve with mumps
#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 0

#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_f0F1_pc_type lu -inner_fieldsplit_f0F1_pc_factor_mat_solver_package mumps -inner_fieldsplit_constraints_pc_type none \
#    -outer_ksp_max_it 10 -inner_fieldsplit_constraints_ksp_type richardson -inner_fieldsplit_constraints_ksp_max_it 1 -inner_ksp_monitor 

# Splitting off constraints, with direct solve on the remainder. Converges in 1 step.
#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_f0F1_pc_type lu -inner_fieldsplit_f0F1_pc_factor_mat_solver_package mumps -inner_fieldsplit_constraints_pc_type jacobi \
#    -outer_ksp_max_it 10 -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_ksp_max_it 1 -inner_ksp_monitor \
#    -outer_ksp_type fgmres

#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_1_pc_type lsc \
#    -inner_fieldsplit_f0F1_fieldsplit_1_lsc_pc_type lu -inner_fieldsplit_constraints_pc_type jacobi \
#    -outer_ksp_max_it 10 -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_ksp_max_it 1 -inner_ksp_monitor \
#    -outer_ksp_type fgmres

# Try preconditioning with [A, 0; 0, I]. Takes 70 iterations.
#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type additive \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_1_pc_type jacobi \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres

# Try preconditioning with Block Seidel based on [A, 0; 0, I] (Same as last case, but replace fieldsplit_type additive -> multiplicative).
# Takes 25 iterations.
#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type multiplicative \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_1_pc_type jacobi \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres

# Try preconditioning with Block Seidel based on [A, 0; 0, I] (Same as last case, but replace fieldsplit_type additive -> symmetric_multiplicative).
# Takes 25 iterations.
#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type symmetric_multiplicative \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_1_pc_type jacobi \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres

# Switching to high-order derivatives. Takes just 27 iterations!
#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 10 -zetaGridScheme 10 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type multiplicative \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_1_pc_type jacobi \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres

# Lower collisionality. Low order derivatives. Takes 37 iterations.
#./mmc -Ntheta 15 -Nzeta 15 -Nxi 30 -nu 0.01 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type multiplicative \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_1_pc_type jacobi \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres

# Nu 0.01, high order derivatives. Takes 37 iterations.
#./mmc -Ntheta 15 -Nzeta 15 -Nxi 30 -nu 0.01 -E 0 -thetaGridScheme 10 -zetaGridScheme 10 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type multiplicative \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_1_pc_type jacobi \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres

# Lower collisionality. Low order derivatives. Converges, but slowly.
#./mmc -Ntheta 27 -Nzeta 29 -Nxi 70 -nu 0.001 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type multiplicative \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_0_pc_factor_mat_solver_package mumps -inner_fieldsplit_f0F1_fieldsplit_1_pc_type jacobi \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres

# Low collisionality. High order derivatives. Converges, but slowly.
#./mmc -Ntheta 27 -Nzeta 29 -Nxi 70 -nu 0.001 -E 0 -thetaGridScheme 10 -zetaGridScheme 10 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type multiplicative \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_0_pc_factor_mat_solver_package mumps -inner_fieldsplit_f0F1_fieldsplit_1_pc_type jacobi \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres

# Highish nu, gamg
#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type multiplicative \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type ilu -inner_fieldsplit_f0F1_fieldsplit_1_pc_type jacobi \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres

# Try diagonal Schur complement method: BuffaloTutorial.pdf slide 175
# Takes 3 outer iterations.
#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type diag -inner_fieldsplit_f0F1_pc_fieldsplit_schur_precondition selfp \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type minres -inner_fieldsplit_f0F1_fieldsplit_1_pc_type none \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor 

# Same, but lower Schur complement, as in BuffaloTutorial.pdf page 176
# Takes 2 outer iterations
#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type lower -inner_fieldsplit_f0F1_pc_fieldsplit_schur_precondition selfp \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type minres -inner_fieldsplit_f0F1_fieldsplit_1_pc_type none \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor

# Same, but upper Schur complement, as in BuffaloTutorial.pdf page 177
# Takes 2 outer iterations
#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type upper -inner_fieldsplit_f0F1_pc_fieldsplit_schur_precondition selfp \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type minres -inner_fieldsplit_f0F1_fieldsplit_1_pc_type none \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor

# High order, modest nu
# Upper Schur complement, as in BuffaloTutorial.pdf page 177
# Takes 2 iterations.
#./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 10 -zetaGridScheme 10 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type upper -inner_fieldsplit_f0F1_pc_fieldsplit_schur_precondition selfp \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type minres -inner_fieldsplit_f0F1_fieldsplit_1_pc_type none \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor

# Low order, nu 0.01
# Upper Schur complement, as in BuffaloTutorial.pdf page 177
# Takes 2 iterations.
#./mmc -Ntheta 13 -Nzeta 15 -Nxi 30 -nu 0.01 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type upper -inner_fieldsplit_f0F1_pc_fieldsplit_schur_precondition selfp \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_0_pc_factor_mat_solver_package mumps \
#    -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type minres -inner_fieldsplit_f0F1_fieldsplit_1_pc_type none \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor

# High order, nu 0.01
# Upper Schur complement, as in BuffaloTutorial.pdf page 177
# Takes 2 iterations.
#./mmc -Ntheta 15 -Nzeta 15 -Nxi 30 -nu 0.01 -E 0 -thetaGridScheme 10 -zetaGridScheme 10 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type upper -inner_fieldsplit_f0F1_pc_fieldsplit_schur_precondition selfp \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_0_pc_factor_mat_solver_package mumps \
#    -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type minres -inner_fieldsplit_f0F1_fieldsplit_1_pc_type none \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor

# Low order, nu 0.001
# Upper Schur complement, as in BuffaloTutorial.pdf page 177
# Takes 2 outer iterations, 239 & 242 minres iterations
#./mmc -Ntheta 27 -Nzeta 29 -Nxi 70 -nu 0.001 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type upper -inner_fieldsplit_f0F1_pc_fieldsplit_schur_precondition selfp \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_0_pc_factor_mat_solver_package mumps \
#    -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type minres -inner_fieldsplit_f0F1_fieldsplit_1_pc_type none \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor

# High order, nu 0.001
# Upper Schur complement, as in BuffaloTutorial.pdf page 177
# Takes 2 outer iterations, 241 & 241 minres iterations
#./mmc -Ntheta 27 -Nzeta 29 -Nxi 70 -nu 0.001 -E 0 -thetaGridScheme 10 -zetaGridScheme 10 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type upper -inner_fieldsplit_f0F1_pc_fieldsplit_schur_precondition a11 \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_0_pc_factor_mat_solver_package mumps \
#    -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type minres -inner_fieldsplit_f0F1_fieldsplit_1_pc_type none \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor

# High order, nu 0.01
# Uzawa, as in BuffaloTutorial.pdf page 178
# Took 37 iterations, same as Jacobi (page 171).
#./mmc -Ntheta 15 -Nzeta 15 -Nxi 30 -nu 0.01 -E 0 -thetaGridScheme 10 -zetaGridScheme 10 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type upper  \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_0_pc_factor_mat_solver_package mumps \
#    -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type richardson -inner_fieldsplit_f0F1_fieldsplit_1_ksp_max_it 1 \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor

# High order, nu 0.01
# Full Schur, as in BuffaloTutorial.pdf page 179. Not converging.
#./mmc -Ntheta 15 -Nzeta 15 -Nxi 30 -nu 0.01 -E 0 -thetaGridScheme 10 -zetaGridScheme 10 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type full  \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_0_pc_factor_mat_solver_package mumps \
#    -inner_fieldsplit_f0F1_fieldsplit_1_pc_type jacobi -inner_fieldsplit_f0F1_fieldsplit_1_ksp_rtol 1e-10 \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor

# High order, nu 0.01
# LSC, as in BuffaloTutorial.pdf page 181. Not converging.
#./mmc -Ntheta 15 -Nzeta 15 -Nxi 30 -nu 0.01 -E 0 -thetaGridScheme 10 -zetaGridScheme 10 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type upper  \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type lu -inner_fieldsplit_f0F1_fieldsplit_0_pc_factor_mat_solver_package mumps \
#    -inner_fieldsplit_f0F1_fieldsplit_1_pc_type lsc -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type minres \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor

# High order, nu 0.001
# Upper Schur complement, as in BuffaloTutorial.pdf page 177
#./mmc -Ntheta 27 -Nzeta 29 -Nxi 70 -nu 0.001 -E 0 -thetaGridScheme 10 -zetaGridScheme 10 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type upper \
#    -inner_fieldsplit_f0F1_fieldsplit_0_ksp_type preonly -inner_fieldsplit_f0F1_fieldsplit_0_pc_type gamg  \
#    -inner_fieldsplit_f0F1_fieldsplit_0_mg_levels_ksp_type richardson -inner_fieldsplit_f0F1_fieldsplit_0_pc_gamg_agg_nsmooths 0 \
#    -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type minres -inner_fieldsplit_f0F1_fieldsplit_1_pc_type none \
#    -outer_ksp_max_it 4  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor 

# High order, nu 0.01
# Upper Schur complement, as in BuffaloTutorial.pdf page 177
#./mmc -Ntheta 15 -Nzeta 15 -Nxi 30 -nu 0.01 -E 0 -thetaGridScheme 10 -zetaGridScheme 10 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type upper \
#    -inner_fieldsplit_f0F1_fieldsplit_0_ksp_type preonly -inner_fieldsplit_f0F1_fieldsplit_0_pc_type gamg \ #-inner_fieldsplit_f0F1_fieldsplit_0_pc_gamg_threshold 0.1 \
#    \ #-inner_fieldsplit_f0F1_fieldsplit_0_mg_levels_ksp_type richardson \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_gamg_agg_nsmooths 0 \
#    -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type minres -inner_fieldsplit_f0F1_fieldsplit_1_pc_type none \
#    -outer_ksp_max_it 10  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_rtol 1e-1  #-inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor 

# High order, nu 0.01
# Upper Schur complement, as in BuffaloTutorial.pdf page 177
#./mmc -Ntheta 15 -Nzeta 15 -Nxi 30 -nu 0.01 -E 0 -thetaGridScheme 10 -zetaGridScheme 10 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type upper \
#    -inner_fieldsplit_f0F1_fieldsplit_0_ksp_type preonly -inner_fieldsplit_f0F1_fieldsplit_0_pc_type gamg \
#    -inner_fieldsplit_f0F1_fieldsplit_0_pc_gamg_agg_nsmooths 0 \
#    -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type minres -inner_fieldsplit_f0F1_fieldsplit_1_pc_type none \
#    -outer_ksp_max_it 1000  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_max_it 2 -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor

# nu 0.01
# Upper Schur complement, as in BuffaloTutorial.pdf page 177
#./mmc -Ntheta 15 -Nzeta 15 -Nxi 30 -nu 0.01 -E 0 -thetaGridScheme 10 -zetaGridScheme 10 -L_scaling_option 1 -fieldsplit_option 1 \
#    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
#    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type schur \
#    -inner_fieldsplit_f0F1_pc_fieldsplit_schur_factorization_type upper \
#    -inner_fieldsplit_f0F1_fieldsplit_0_ksp_type preonly -inner_fieldsplit_f0F1_fieldsplit_0_pc_type gamg \
#    -inner_fieldsplit_f0F1_fieldsplit_1_ksp_type minres -inner_fieldsplit_f0F1_fieldsplit_1_pc_type none \
#    -outer_ksp_max_it 100  -outer_ksp_type fgmres -inner_fieldsplit_f0F1_fieldsplit_1_ksp_monitor

# Nu 0.01. Block Gauss Seidel preconditioning
./mmc -Ntheta 15 -Nzeta 15 -Nxi 30 -nu 0.01 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -L_scaling_option 1 -fieldsplit_option 1 \
    -inner_fieldsplit_constraints_ksp_type preonly -inner_fieldsplit_constraints_pc_type jacobi \
    -inner_fieldsplit_f0F1_pc_type fieldsplit -inner_fieldsplit_f0F1_pc_fieldsplit_detect_saddle_point -inner_fieldsplit_f0F1_pc_fieldsplit_type multiplicative \
    -inner_fieldsplit_f0F1_fieldsplit_0_pc_type gamg -inner_fieldsplit_f0F1_fieldsplit_1_pc_type jacobi \
    -outer_ksp_max_it 100  -outer_ksp_type fgmres
