#!/bin/bash

#mpiexec -n 1 ./mmc -options_left -ksp_view

#mpiexec -n 3 ./mmc -options_left -ksp_view -pc_factor_mat_solver_package mumps

#mpiexec -n 4 ./mmc -options_left -ksp_view -pc_factor_mat_solver_package mumps -mat_mumps_icntl_4 2

./mmc -Ntheta 13 -Nzeta 15 -Nxi 16 -nu 0.1 -E 0 -thetaGridScheme 0 -zetaGridScheme 0 -pc_factor_mat_solver_package mumps